services:
  - type: web
    name: novatrade-bus
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: OUTBOX_DB_PATH
        value: /data/outbox.db
      - key: OUTBOX_SECRET
        value: ${OUTBOX_SECRET}
      - key: EDGE_SECRET
        value: ${OUTBOX_SECRET}
      - key: OUTBOX_AGENT_ALLOW
        value: edge-cb-1
      - key: REQUIRE_HMAC_PULL
        value: "1"
      - key: REQUIRE_HMAC_OPS
        value: "1"
      - key: OUTBOX_LEASE_S
        value: "120"
      - key: RUN_BOOT_IN_WSGI
        value: "1"
      - key: RUN_WEBHOOK_IN_MAIN
        value: "0"
      - key: SHEET_URL
        value: ${SHEET_URL}
      - key: GOOGLE_CREDS_JSON_PATH
        value: sentiment-log-service.json
      # Optional if you choose Option B (decode in start.sh)
      # - key: GOOGLE_CREDS_JSON_B64
      #   value: ${GOOGLE_CREDS_JSON_B64}
    plan: starter
    autoDeploy: true
    disk:
      name: outbox-data
      mountPath: /data
      sizeGB: 1

  - type: worker
    name: novatrade-edge
    env: docker
    dockerfilePath: Dockerfile.edge
    envVars:
      - key: CLOUD_BASE_URL
        value: https://novatrade-bus.onrender.com
      - key: AGENT_ID
        value: edge-cb-1
      - key: EDGE_SECRET
        value: ${OUTBOX_SECRET}
      - key: EDGE_MODE
        value: dryrun
      - key: EDGE_HOLD
        value: "false"
      - key: EDGE_POLL_SECS
        value: "10"
      - key: COINBASE_API_KEY
        value: ${COINBASE_API_KEY}
      - key: COINBASE_API_SECRET
        value: ${COINBASE_API_SECRET}
      - key: BINANCEUS_API_KEY
        value: ${BINANCEUS_API_KEY}
      - key: BINANCEUS_API_SECRET
        value: ${BINANCEUS_API_SECRET}
      - key: KRAKEN_KEY
        value: ${KRAKEN_KEY}
      - key: KRAKEN_SECRET
        value: ${KRAKEN_SECRET}
    plan: starter
